# Generated by Django 3.1.7 on 2021-04-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_birthday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
