# Generated by Django 3.1.7 on 2021-04-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relation_with_minki',
            field=models.SmallIntegerField(choices=[(0, '가족 혹은 친척'), (1, '친구'), (2, '지인'), (3, '누군지 모르는')]),
        ),
    ]
