# Generated by Django 3.1.7 on 2021-04-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210422_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='적지 않아도 괜찮습니다.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='relation_with_minki',
            field=models.SmallIntegerField(choices=[(0, '가족 혹은 친척'), (1, '친구'), (2, '지인'), (3, '이제부터 알아갈게요')], default=2),
        ),
    ]
